import type { PluginContext } from "@paperclipai/plugin-sdk";
import manifest from "./manifest.js";
import { PLUGIN_ID } from "./constants.js";
import type { HonchoResolvedConfig } from "./types.js";

// Bump whenever buildBridgeScriptSource()'s behavior changes so existing
// agent runtime homes pick up the new version instead of staying frozen on
// whatever was written the first time repairMappings ran.
export const MCP_BRIDGE_VERSION = "2";

export const AGENT_RUNTIME_FOLDER_KEY = "agent-runtime-home";
export const BRIDGE_SCRIPT_FILENAME = "paperclip-honcho-mcp-bridge.cjs";
const MCP_SERVER_KEY = "paperclip_honcho";
const VERSION_MARKER_PREFIX = "# paperclip-honcho-mcp-bridge version:";

function toolDeclarationsJson(): string {
  const tools = (manifest.tools ?? []).map((tool) => ({
    name: tool.name,
    description: tool.description,
    inputSchema: tool.parametersSchema,
  }));
  return JSON.stringify(tools, null, 2);
}

// Standalone, dependency-free (Node built-ins only) MCP stdio server. It is
// never bundled/shipped as a build artifact: the source lives here as a
// string and is written out fresh, by the running plugin worker, into an
// operator-configured agent runtime home. It proxies every MCP tool call to
// this same plugin's already-working `/api/plugins/tools/execute` endpoint
// using the env vars Paperclip already injects into every agent run
// (PAPERCLIP_API_URL, PAPERCLIP_API_KEY, PAPERCLIP_AGENT_ID,
// PAPERCLIP_COMPANY_ID, PAPERCLIP_RUN_ID), so it reuses the real tool
// implementations instead of re-deriving Honcho workspace/session/peer ids
// itself.
export function buildBridgeScriptSource(): string {
  return `#!/usr/bin/env node
// Generated by @honcho-ai/paperclip-honcho. Do not edit by hand — it is
// regenerated whenever the plugin syncs this agent runtime home, and any
// manual edits will be silently overwritten.
// version: ${MCP_BRIDGE_VERSION}
"use strict";

const http = require("http");
const https = require("https");

const PLUGIN_TOOL_PREFIX = ${JSON.stringify(PLUGIN_ID)};
const TOOLS = ${toolDeclarationsJson()};

const PAPERCLIP_API_URL = (process.env.PAPERCLIP_API_URL || "").replace(/\\/+$/, "");
const PAPERCLIP_API_KEY = process.env.PAPERCLIP_API_KEY || "";
const PAPERCLIP_AGENT_ID = process.env.PAPERCLIP_AGENT_ID || "";
const PAPERCLIP_COMPANY_ID = process.env.PAPERCLIP_COMPANY_ID || "";
const PAPERCLIP_RUN_ID = process.env.PAPERCLIP_RUN_ID || "";

let cachedProjectId = process.env.PAPERCLIP_PROJECT_ID || null;

function paperclipRequest(requestPath, method, body) {
  return new Promise((resolve, reject) => {
    if (!PAPERCLIP_API_URL) {
      reject(new Error("PAPERCLIP_API_URL is not set in this run's environment."));
      return;
    }
    let url;
    try {
      url = new URL(PAPERCLIP_API_URL + requestPath);
    } catch (error) {
      reject(error);
      return;
    }
    const lib = url.protocol === "http:" ? http : https;
    const payload = body !== undefined ? JSON.stringify(body) : undefined;
    const req = lib.request(
      url,
      {
        method,
        headers: Object.assign(
          { "Content-Type": "application/json" },
          PAPERCLIP_API_KEY ? { Authorization: "Bearer " + PAPERCLIP_API_KEY } : {},
          payload !== undefined ? { "Content-Length": Buffer.byteLength(payload) } : {},
        ),
      },
      (res) => {
        let data = "";
        res.on("data", (chunk) => { data += chunk; });
        res.on("end", () => {
          let parsed = null;
          try { parsed = data ? JSON.parse(data) : null; } catch { parsed = null; }
          const status = res.statusCode || 0;
          if (status >= 400) {
            const message = parsed && parsed.error ? parsed.error : "HTTP " + status;
            reject(new Error(message));
            return;
          }
          resolve(parsed);
        });
      },
    );
    req.on("error", reject);
    if (payload !== undefined) req.write(payload);
    req.end();
  });
}

async function resolveProjectId() {
  if (cachedProjectId) return cachedProjectId;
  const projects = await paperclipRequest(
    "/api/companies/" + encodeURIComponent(PAPERCLIP_COMPANY_ID) + "/projects",
    "GET",
  );
  const list = Array.isArray(projects) ? projects : Array.isArray(projects && projects.items) ? projects.items : [];
  const first = list[0];
  if (!first || !first.id) {
    throw new Error("No project found for this company; the Honcho tool bridge needs at least one project to exist.");
  }
  cachedProjectId = first.id;
  return cachedProjectId;
}

async function callPluginTool(name, args) {
  if (!PAPERCLIP_AGENT_ID || !PAPERCLIP_COMPANY_ID || !PAPERCLIP_RUN_ID) {
    throw new Error("This run's environment is missing PAPERCLIP_AGENT_ID/PAPERCLIP_COMPANY_ID/PAPERCLIP_RUN_ID.");
  }
  const projectId = await resolveProjectId();
  const result = await paperclipRequest("/api/plugins/tools/execute", "POST", {
    tool: PLUGIN_TOOL_PREFIX + ":" + name,
    parameters: args || {},
    runContext: {
      agentId: PAPERCLIP_AGENT_ID,
      runId: PAPERCLIP_RUN_ID,
      companyId: PAPERCLIP_COMPANY_ID,
      projectId,
    },
  });
  return result || {};
}

function send(message) {
  process.stdout.write(JSON.stringify(message) + "\\n");
}

function sendResult(id, result) {
  send({ jsonrpc: "2.0", id, result });
}

function sendError(id, code, message) {
  send({ jsonrpc: "2.0", id, error: { code, message } });
}

async function handleRequest(message) {
  const id = message.id;
  const method = message.method;
  const params = message.params;
  try {
    if (method === "initialize") {
      sendResult(id, {
        protocolVersion: (params && params.protocolVersion) || "2025-06-18",
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: "paperclip-honcho", version: ${JSON.stringify(MCP_BRIDGE_VERSION)} },
      });
      return;
    }
    if (method === "notifications/initialized" || method === "initialized" || method === "notifications/cancelled") {
      return;
    }
    if (method === "ping") {
      sendResult(id, {});
      return;
    }
    if (method === "tools/list") {
      sendResult(id, { tools: TOOLS });
      return;
    }
    if (method === "tools/call") {
      const name = params && params.name;
      const args = (params && params.arguments) || {};
      if (!name || typeof name !== "string") {
        sendError(id, -32602, "Missing tool name");
        return;
      }
      try {
        const result = await callPluginTool(name, args);
        const text = typeof result.content === "string"
          ? result.content
          : JSON.stringify(result.data !== undefined ? result.data : result);
        sendResult(id, {
          content: [{ type: "text", text: text || "(empty result)" }],
          isError: Boolean(result.error),
        });
      } catch (error) {
        sendResult(id, {
          content: [{ type: "text", text: "Honcho tool call failed: " + (error && error.message ? error.message : String(error)) }],
          isError: true,
        });
      }
      return;
    }
    if (id !== undefined) {
      sendError(id, -32601, "Method not found: " + method);
    }
  } catch (error) {
    if (id !== undefined) {
      sendError(id, -32603, error && error.message ? error.message : String(error));
    }
  }
}

let buffer = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
  buffer += chunk;
  let newlineIndex;
  while ((newlineIndex = buffer.indexOf("\\n")) >= 0) {
    const line = buffer.slice(0, newlineIndex).trim();
    buffer = buffer.slice(newlineIndex + 1);
    if (!line) continue;
    let message;
    try {
      message = JSON.parse(line);
    } catch {
      continue;
    }
    void handleRequest(message);
  }
});
process.stdin.on("end", () => {
  process.exit(0);
});
`;
}

function stripExistingBridgeBlock(tomlText: string): string {
  const markerIndex = tomlText.indexOf(VERSION_MARKER_PREFIX);
  if (markerIndex === -1) return tomlText.trimEnd();
  const blockStart = tomlText.lastIndexOf("\n", markerIndex) + 1;
  // Skip past our own table header before looking for the *next* table, or
  // the search below would immediately match our own header line (it always
  // follows the marker directly) and leave the rest of our block behind.
  const ownHeader = `[mcp_servers.${MCP_SERVER_KEY}]`;
  const ownHeaderIndex = tomlText.indexOf(ownHeader, markerIndex);
  const searchFrom = ownHeaderIndex === -1
    ? markerIndex + VERSION_MARKER_PREFIX.length
    : ownHeaderIndex + ownHeader.length;
  const nextHeaderMatch = /\n\[/.exec(tomlText.slice(searchFrom));
  const blockEnd = nextHeaderMatch ? searchFrom + nextHeaderMatch.index + 1 : tomlText.length;
  return (tomlText.slice(0, blockStart) + tomlText.slice(blockEnd)).trimEnd();
}

// Codex does not inherit the launching process's environment into a spawned
// MCP server by default — `env_vars` explicitly forwards named variables
// from the run's own environment. Without this, the bridge script has no
// way to know which agent/company/run it's answering for.
const FORWARDED_ENV_VARS = [
  "PAPERCLIP_API_URL",
  "PAPERCLIP_API_KEY",
  "PAPERCLIP_AGENT_ID",
  "PAPERCLIP_COMPANY_ID",
  "PAPERCLIP_RUN_ID",
  "PAPERCLIP_PROJECT_ID",
];

function buildBridgeTomlBlock(scriptAbsolutePath: string): string {
  return [
    "",
    `${VERSION_MARKER_PREFIX} ${MCP_BRIDGE_VERSION}`,
    `[mcp_servers.${MCP_SERVER_KEY}]`,
    "command = \"node\"",
    `args = [${JSON.stringify(scriptAbsolutePath)}]`,
    `env_vars = ${JSON.stringify(FORWARDED_ENV_VARS)}`,
    "startup_timeout_sec = 20",
    "",
  ].join("\n");
}

export type McpBridgeSyncResult =
  | { status: "skipped" }
  | { status: "synced" }
  | { status: "failed"; message: string };

// Idempotent: safe to call on every repairMappings pass. Writes are skipped
// when content already matches, and the config.toml block is replaced
// wholesale (not blindly appended) keyed off the version marker, so
// upgrading the plugin's bridge script never leaves a stale duplicate table
// behind.
export async function syncAgentRuntimeMcpBridge(
  ctx: PluginContext,
  companyId: string,
  config: HonchoResolvedConfig,
): Promise<McpBridgeSyncResult> {
  const template = config.agentRuntimeHomePathTemplate.trim();
  if (!template) return { status: "skipped" };

  const targetPath = template.replaceAll("{companyId}", companyId);

  try {
    await ctx.localFolders.configure({
      companyId,
      folderKey: AGENT_RUNTIME_FOLDER_KEY,
      path: targetPath,
      access: "readWrite",
    });

    const status = await ctx.localFolders.status(companyId, AGENT_RUNTIME_FOLDER_KEY);
    if (!status.healthy || !status.realPath) {
      const message = status.problems.map((problem) => problem.message).join("; ") || "Agent runtime home is not ready.";
      return { status: "failed", message };
    }

    const scriptSource = buildBridgeScriptSource();
    const existingScript = await ctx.localFolders
      .readText(companyId, AGENT_RUNTIME_FOLDER_KEY, BRIDGE_SCRIPT_FILENAME)
      .catch(() => null);
    if (existingScript !== scriptSource) {
      await ctx.localFolders.writeTextAtomic(companyId, AGENT_RUNTIME_FOLDER_KEY, BRIDGE_SCRIPT_FILENAME, scriptSource);
    }

    const scriptAbsolutePath = `${status.realPath.replace(/\/+$/, "")}/${BRIDGE_SCRIPT_FILENAME}`;
    const existingToml = await ctx.localFolders
      .readText(companyId, AGENT_RUNTIME_FOLDER_KEY, "config.toml")
      .catch(() => "");
    const nextToml = `${stripExistingBridgeBlock(existingToml)}\n${buildBridgeTomlBlock(scriptAbsolutePath)}`;
    if (nextToml.trim() !== existingToml.trim()) {
      await ctx.localFolders.writeTextAtomic(companyId, AGENT_RUNTIME_FOLDER_KEY, "config.toml", nextToml);
    }

    return { status: "synced" };
  } catch (error) {
    return { status: "failed", message: error instanceof Error ? error.message : String(error) };
  }
}
